name: Build COSMIC copr

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14 * * *" # 2pm UTC everyday (timed against official fedora container pushes)

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  COPR_AUTH: ${{ secrets.COPR_AUTH }}
  PAT_GITHUB: ${{ secrets.PAT_GITHUB }}

jobs:
  build:
    name: Build 
    runs-on: ubuntu-22.04
    container: fedora:latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
    steps:
      - run: echo ${{env.COPR_AUTH}} >> ~/.config/copr
      - uses: actions/checkout@v4
      - run: sudo dnf install -y copr-cli
      - run: python3 ./copr-build.py